### ISSUE TITLE
Cannot request KCS from https://faucet-testnet.kucoin.one due to CAPTCHA ERROR

### ISSUE THREAD

**Issue by michiboo** [kcc-community/kcc-testnet-faucet#7]
![image](https://user-images.githubusercontent.com/26637492/123503062-0ce00580-d683-11eb-855e-a1c0aeb92a16.png)

**Comment by lingyun92** [comment]
https://faucet-testnet.kcc.network/

**Comment by Ikenna160** [comment]
> https://faucet-testnet.kcc.network/

Is it working for you?

**Comment by lingyun92** [comment]
yes
